import { Role } from "@prisma/client";

export const roleLabels: Record<Role, string> = {
  SUPER_ADMIN: "مدير عام",
  ADMIN: "مدير",
  UNDERWRITER: "مكتتب",
  FINANCE: "مالية",
  AGENT: "وكيل",
  BANK: "صلاحية البنوك",
  VIEWER: "مشاهد"
};

const permissions = {
  dashboard: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.FINANCE, Role.AGENT, Role.BANK, Role.VIEWER],
  customersRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.FINANCE, Role.AGENT, Role.VIEWER],
  customersWrite: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.AGENT],
  customersDelete: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  policiesRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.FINANCE, Role.AGENT, Role.VIEWER],
  plansWrite: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  countriesWrite: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  policiesWrite: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.AGENT],
  policiesManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  policiesDelete: [Role.SUPER_ADMIN],
  financeRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.FINANCE],
  motorAccountsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.FINANCE],
  motorCommissionsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.FINANCE],
  motorCommissionsWrite: [Role.SUPER_ADMIN, Role.ADMIN, Role.FINANCE],
  claimsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  claimsWrite: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.AGENT],
  claimsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  reportsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.FINANCE, Role.AGENT],
  referralsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.FINANCE, Role.BANK],
  referralsCreate: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.BANK],
  referralsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  referralsDelete: [Role.SUPER_ADMIN],
  referralCommissionsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.FINANCE],
  referralCommissionsWrite: [Role.SUPER_ADMIN, Role.ADMIN, Role.FINANCE],
  referralReportsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.FINANCE],
  reportRequestsCreate: [Role.BANK],
  reportRequestsRead: [Role.BANK],
  reportRequestsManage: [Role.SUPER_ADMIN],
  auditRead: [Role.SUPER_ADMIN, Role.ADMIN],
  notificationsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER, Role.FINANCE, Role.VIEWER],
  endorsementsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  endorsementsWrite: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  cancellationsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  cancellationsWrite: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  agencyRead: [Role.SUPER_ADMIN, Role.ADMIN],
  agentsManage: [Role.SUPER_ADMIN, Role.ADMIN],
  agentAccountsRead: [Role.SUPER_ADMIN],
  motorRequestsCreate: [],
  motorRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  motorRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  motorRequestsEdit: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  motorRequestsDelete: [Role.SUPER_ADMIN],
  motorRequestsPricing: [Role.SUPER_ADMIN, Role.UNDERWRITER],
  motorRequestsTermsWrite: [Role.SUPER_ADMIN, Role.UNDERWRITER],
  motorRequestsTermsApprove: [Role.SUPER_ADMIN],
  motorRequestsApprovalAssets: [Role.SUPER_ADMIN, Role.UNDERWRITER],
  travelRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  travelRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  fireRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  fireRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  contractorsAllRisksRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  contractorsAllRisksRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  publicLiabilityRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  publicLiabilityRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  workersCompensationRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  workersCompensationRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  glassRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  glassRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  healthRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  healthRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  propertyRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  propertyRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  fidelityGuaranteeRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  fidelityGuaranteeRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  cashInsuranceRequestsRead: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  cashInsuranceRequestsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER],
  systemManage: [Role.SUPER_ADMIN, Role.ADMIN],
  lookupsManage: [Role.SUPER_ADMIN, Role.ADMIN, Role.UNDERWRITER]
} as const;

export type Permission = keyof typeof permissions;

export function can(role: Role | undefined, permission: Permission) {
  return Boolean(role && (permissions[permission] as readonly Role[]).includes(role));
}
